.TH "_IFAPI_CRYPTO_CONTEXT" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_IFAPI_CRYPTO_CONTEXT
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const EVP_MD * \fBosslHashAlgorithm\fP"
.br
.ti -1c
.RI "EVP_MD_CTX * \fBosslContext\fP"
.br
.ti -1c
.RI "size_t \fBhashSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Context to hold temporary values for ifapi_crypto 
.SH "Field Documentation"
.PP 
.SS "size_t hashSize"
The size of the hash's digest 
.SS "EVP_MD_CTX* osslContext"
The hash engine's context 
.SS "const EVP_MD* osslHashAlgorithm"
The currently used hash algorithm 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
