.TH "esys" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esys \- Enhanced System API (ESAPI) as described in the \fCTSS 2\&.0 Enhanced System API (ESAPI) Specification\fP\&. This API is a 1-to-1 mapping of the TPM2 commands documented in Part 3 of the TPM2 specification\&. Additionally there are asynchronous versions of each command\&. In addition to SAPI, the ESAPI performs tracking of meta data for TPM object and automatic calculation of session based authorization and encryption values\&. Both the synchronous and asynchronous API are exposed through a single library: libtss2-esys\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBEsys Context ESYS_CONTEXT\fP"
.br
.ti -1c
.RI "\fBEsys Tpm Resource ESYS_TR\fP"
.br
.ti -1c
.RI "\fBEsys TPM Commands\fP"
.br
.ti -1c
.RI "\fBInternals of Enhanced System API\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enhanced System API (ESAPI) as described in the \fCTSS 2\&.0 Enhanced System API (ESAPI) Specification\fP\&. This API is a 1-to-1 mapping of the TPM2 commands documented in Part 3 of the TPM2 specification\&. Additionally there are asynchronous versions of each command\&. In addition to SAPI, the ESAPI performs tracking of meta data for TPM object and automatic calculation of session based authorization and encryption values\&. Both the synchronous and asynchronous API are exposed through a single library: libtss2-esys\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
