.TH "ESYS_CRYPTO_CALLBACKS" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ESYS_CRYPTO_CALLBACKS
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ESYS_CRYPTO_PK_RSA_ENCRYPT_FNP \fBrsa_pk_encrypt\fP"
.br
.ti -1c
.RI "ESYS_CRYPTO_HASH_START_FNP \fBhash_start\fP"
.br
.ti -1c
.RI "ESYS_CRYPTO_HASH_UPDATE_FNP \fBhash_update\fP"
.br
.ti -1c
.RI "ESYS_CRYPTO_HASH_FINISH_FNP \fBhash_finish\fP"
.br
.ti -1c
.RI "ESYS_CRYPTO_HASH_ABORT_FNP \fBhash_abort\fP"
.br
.ti -1c
.RI "ESYS_CRYPTO_HMAC_START_FNP \fBhmac_start\fP"
.br
.ti -1c
.RI "ESYS_CRYPTO_HMAC_UPDATE_FNP \fBhmac_update\fP"
.br
.ti -1c
.RI "ESYS_CRYPTO_HMAC_FINISH_FNP \fBhmac_finish\fP"
.br
.ti -1c
.RI "ESYS_CRYPTO_HMAC_ABORT_FNP \fBhmac_abort\fP"
.br
.ti -1c
.RI "ESYS_CRYPTO_GET_RANDOM2B_FNP \fBget_random2b\fP"
.br
.ti -1c
.RI "ESYS_CRYPTO_GET_ECDH_POINT_FNP \fBget_ecdh_point\fP"
.br
.ti -1c
.RI "ESYS_CRYPTO_AES_ENCRYPT_FNP \fBaes_encrypt\fP"
.br
.ti -1c
.RI "ESYS_CRYPTO_AES_DECRYPT_FNP \fBaes_decrypt\fP"
.br
.ti -1c
.RI "ESYS_CRYPTO_INIT_FNP \fBinit\fP"
.br
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
