.TH "Fapi_Free" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fapi_Free \- FAPI function to invoke Free\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBFapi_Free\fP (void *ptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
FAPI function to invoke Free\&. 


.SH "Function Documentation"
.PP 
.SS "Fapi_Free (void * ptr)"
Frees a FAPI allocated return buffer\&.
.PP
Fapi_Free is a helper function that is a wrapper around free()\&. This allows programs that are built using a different version of the C runtime to free memory that has been allocated by the esys library on Windows\&.
.PP
\fBParameters\fP
.RS 4
\fIptr\fP A pointer to the object that is to be freed\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
