.TH "Fapi_GetCertificate" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fapi_GetCertificate \- FAPI functions to invoke GetCertificate either as one-call or in an asynchronous manner\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "TSS2_RC \fBFapi_GetCertificate\fP (\fBFAPI_CONTEXT\fP *context, char const *path, char **x509certData)"
.br
.ti -1c
.RI "TSS2_RC \fBFapi_GetCertificate_Async\fP (\fBFAPI_CONTEXT\fP *context, char const *path)"
.br
.ti -1c
.RI "TSS2_RC \fBFapi_GetCertificate_Finish\fP (\fBFAPI_CONTEXT\fP *context, char **x509certData)"
.br
.in -1c
.SH "Detailed Description"
.PP 
FAPI functions to invoke GetCertificate either as one-call or in an asynchronous manner\&. 


.SH "Function Documentation"
.PP 
.SS "TSS2_RC Fapi_GetCertificate (\fBFAPI_CONTEXT\fP * context, char const * path, char ** x509certData)"
One-Call function for Fapi_GetCertificate
.PP
Gets an x\&.509 certificate for the key at a given path\&.
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP The \fBFAPI_CONTEXT\fP 
.br
\fIpath\fP The path to the key whose certificate is created 
.br
\fIx509certData\fP The PEM-encoded certificate
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP if the function call was a success\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP if context, path or x509CertData is NULL\&. 
.br
\fITSS2_FAPI_RC_BAD_CONTEXT\fP if context corruption is detected\&. 
.br
\fITSS2_FAPI_RC_PATH_NOT_FOUND\fP if path does not map to a FAPI entity\&. 
.br
\fITSS2_FAPI_RC_BAD_KEY\fP if the key is unsuitable for the requested operation\&. 
.br
\fITSS2_FAPI_RC_NO_CERTIFICATE\fP if there is not a x\&.509 cert associated with the path of the key\&. 
.br
\fITSS2_FAPI_RC_BAD_SEQUENCE\fP if the context has an asynchronous operation already pending\&. 
.br
\fITSS2_FAPI_RC_IO_ERROR\fP if the data cannot be saved\&. 
.br
\fITSS2_FAPI_RC_MEMORY\fP if the FAPI cannot allocate enough memory for internal operations or return parameters\&. 
.br
\fITSS2_FAPI_RC_KEY_NOT_FOUND\fP if a key was not found\&. 
.br
\fITSS2_FAPI_RC_BAD_VALUE\fP if an invalid value was passed into the function\&. 
.br
\fITSS2_FAPI_RC_TRY_AGAIN\fP if an I/O operation is not finished yet and this function needs to be called again\&. 
.br
\fITSS2_FAPI_RC_GENERAL_FAILURE\fP if an internal error occurred\&. 
.br
\fITSS2_FAPI_RC_NOT_PROVISIONED\fP FAPI was not provisioned\&. 
.br
\fITSS2_FAPI_RC_BAD_PATH\fP if the path is used in inappropriate context or contains illegal characters\&. 
.RE
.PP

.SS "TSS2_RC Fapi_GetCertificate_Async (\fBFAPI_CONTEXT\fP * context, char const * path)"
Asynchronous function for Fapi_GetCertificate
.PP
Gets an x\&.509 certificate for the key at a given path\&.
.PP
Call Fapi_GetCertificate_Finish to finish the execution of this command\&.
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP The \fBFAPI_CONTEXT\fP 
.br
\fIpath\fP The path to the key whose certificate is created
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP if the function call was a success\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP if context or path is NULL\&. 
.br
\fITSS2_FAPI_RC_BAD_CONTEXT\fP if context corruption is detected\&. 
.br
\fITSS2_FAPI_RC_PATH_NOT_FOUND\fP if path does not map to a FAPI entity\&. 
.br
\fITSS2_FAPI_RC_BAD_KEY\fP if the key is unsuitable for the requested operation\&. 
.br
\fITSS2_FAPI_RC_NO_CERTIFICATE\fP if there is not a x\&.509 cert associated with the path of the key\&. 
.br
\fITSS2_FAPI_RC_BAD_SEQUENCE\fP if the context has an asynchronous operation already pending\&. 
.br
\fITSS2_FAPI_RC_IO_ERROR\fP if the data cannot be saved\&. 
.br
\fITSS2_FAPI_RC_MEMORY\fP if the FAPI cannot allocate enough memory for internal operations or return parameters\&. 
.br
\fITSS2_FAPI_RC_KEY_NOT_FOUND\fP if a key was not found\&. 
.br
\fITSS2_FAPI_RC_BAD_VALUE\fP if an invalid value was passed into the function\&. 
.br
\fITSS2_FAPI_RC_NOT_PROVISIONED\fP FAPI was not provisioned\&. 
.br
\fITSS2_FAPI_RC_BAD_PATH\fP if the path is used in inappropriate context or contains illegal characters\&. 
.RE
.PP

.SS "TSS2_RC Fapi_GetCertificate_Finish (\fBFAPI_CONTEXT\fP * context, char ** x509certData)"
Asynchronous finish function for Fapi_GetCertificate
.PP
This function should be called after a previous Fapi_GetCertificate_Async\&.
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP The \fBFAPI_CONTEXT\fP 
.br
\fIx509certData\fP The PEM-encoded certificate
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP if the function call was a success\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP if context or x509certData is NULL\&. 
.br
\fITSS2_FAPI_RC_BAD_CONTEXT\fP if context corruption is detected\&. 
.br
\fITSS2_FAPI_RC_BAD_SEQUENCE\fP if the context has an asynchronous operation already pending\&. 
.br
\fITSS2_FAPI_RC_IO_ERROR\fP if the data cannot be saved\&. 
.br
\fITSS2_FAPI_RC_MEMORY\fP if the FAPI cannot allocate enough memory for internal operations or return parameters\&. 
.br
\fITSS2_FAPI_RC_TRY_AGAIN\fP if the asynchronous operation is not yet complete\&. Call this function again later\&. 
.br
\fITSS2_FAPI_RC_GENERAL_FAILURE\fP if an internal error occurred\&. 
.br
\fITSS2_FAPI_RC_BAD_VALUE\fP if an invalid value was passed into the function\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
