.TH "Fapi_Finalize" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fapi_Finalize \- FAPI function to invoke Finalize\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBFapi_Finalize\fP (\fBFAPI_CONTEXT\fP **context)"
.br
.in -1c
.SH "Detailed Description"
.PP 
FAPI function to invoke Finalize\&. 


.SH "Function Documentation"
.PP 
.SS "Fapi_Finalize (\fBFAPI_CONTEXT\fP ** context)"
One-Call function for Fapi_Finalize
.PP
\fBFapi_Finalize()\fP finalizes a context by closing IPC/RPC connections and freeing its consumed memory\&.
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP The \fBFAPI_CONTEXT\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
