.TH "FAPI_CONTEXT" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FAPI_CONTEXT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fapi_int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBESYS_CONTEXT\fP * \fBesys\fP"
.br
.ti -1c
.RI "struct \fBIFAPI_CALLBACKS\fP \fBcallbacks\fP"
.br
.ti -1c
.RI "struct \fBIFAPI_IO\fP \fBio\fP"
.br
.ti -1c
.RI "struct \fBIFAPI_EVENTLOG\fP \fBeventlog\fP"
.br
.ti -1c
.RI "struct \fBIFAPI_KEYSTORE\fP \fBkeystore\fP"
.br
.ti -1c
.RI "struct \fBIFAPI_POLICY_STORE\fP \fBpstore\fP"
.br
.ti -1c
.RI "struct \fBIFAPI_PROFILES\fP \fBprofiles\fP"
.br
.ti -1c
.RI "TPMS_TIME_INFO \fBinit_time\fP"
.br
.ti -1c
.RI "enum _FAPI_STATE \fBstate\fP"
.br
.ti -1c
.RI "enum _FAPI_STATE_PRIMARY \fBprimary_state\fP"
.br
.ti -1c
.RI "enum _FAPI_STATE_SESSION \fBsession_state\fP"
.br
.ti -1c
.RI "enum _FAPI_STATE_GET_RANDOM \fBget_random_state\fP"
.br
.ti -1c
.RI "enum IFAPI_HIERACHY_AUTHORIZATION_STATE \fBhierarchy_state\fP"
.br
.ti -1c
.RI "enum IFAPI_HIERACHY_POLICY_AUTHORIZATION_STATE \fBhierarchy_policy_state\fP"
.br
.ti -1c
.RI "enum IFAPI_GET_CERT_STATE \fBget_cert_state\fP"
.br
.ti -1c
.RI "enum _FAPI_FLUSH_STATE \fBflush_object_state\fP"
.br
.ti -1c
.RI "enum IFAPI_CLEANUP_STATE \fBcleanup_state\fP"
.br
.ti -1c
.RI "enum IFAPI_READ_NV_PUBLIC_STATE \fBread_nv_public_state\fP"
.br
.ti -1c
.RI "\fBIFAPI_CONFIG\fP \fBconfig\fP"
.br
.ti -1c
.RI "UINT32 \fBnv_buffer_max\fP"
.br
.ti -1c
.RI "\fBIFAPI_CMD_STATE\fP \fBcmd\fP"
.br
.ti -1c
.RI "\fBIFAPI_NV_Cmds\fP \fBnv_cmd\fP"
.br
.ti -1c
.RI "\fBIFAPI_GetRandom\fP \fBget_random\fP"
.br
.ti -1c
.RI "\fBIFAPI_CreatePrimary\fP \fBcreatePrimary\fP"
.br
.ti -1c
.RI "\fBIFAPI_LoadKey\fP \fBloadKey\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBsession1\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBsession2\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBpolicy_session\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBek_handle\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBsrk_handle\fP"
.br
.ti -1c
.RI "TPMI_DH_PERSISTENT \fBek_persistent\fP"
.br
.ti -1c
.RI "TPMI_DH_PERSISTENT \fBsrk_persistent\fP"
.br
.ti -1c
.RI "IFAPI_SESSION_TYPE \fBsession_flags\fP"
.br
.ti -1c
.RI "TPMA_SESSION \fBsession1_attribute_flags\fP"
.br
.ti -1c
.RI "TPMA_SESSION \fBsession2_attribute_flags\fP"
.br
.ti -1c
.RI "\fBIFAPI_MAX_BUFFER\fP \fBaux_data\fP"
.br
.ti -1c
.RI "\fBIFAPI_POLICY_CTX\fP \fBpolicy\fP"
.br
.ti -1c
.RI "\fBIFAPI_FILE_SEARCH_CTX\fP \fBfsearch\fP"
.br
.ti -1c
.RI "\fBIFAPI_Key_Sign\fP \fBKey_Sign\fP"
.br
.ti -1c
.RI "enum IFAPI_IO_STATE \fBio_state\fP"
.br
.ti -1c
.RI "\fBNODE_OBJECT_T\fP * \fBobject_list\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP * \fBduplicate_key\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP * \fBcurrent_auth_object\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The data structure holding internal state information\&.
.PP
Each \fBFAPI_CONTEXT\fP respresents a logically independent connection to the TPM\&. It stores meta data information about object in order to calculate session auths and similar things\&. 
.SH "Field Documentation"
.PP 
.SS "\fBIFAPI_MAX_BUFFER\fP aux_data"
tpm2b data to be transferred 
.SS "struct \fBIFAPI_CALLBACKS\fP callbacks"
Callbacks for user interaction from FAPI 
.SS "enum IFAPI_CLEANUP_STATE cleanup_state"
The state of cleanup after command execution 
.SS "\fBIFAPI_CMD_STATE\fP cmd"
The state information of the currently executed command 
.SS "\fBIFAPI_CONFIG\fP config"
The profile independent configuration data 
.SS "\fBIFAPI_OBJECT\fP* duplicate_key"
Will be needed for policy execution 
.SS "\fBESYS_CONTEXT\fP* esys"
The ESYS context used internally to talk to the TPM\&. 
.SS "enum _FAPI_FLUSH_STATE flush_object_state"
The current state of a flush operation 
.SS "\fBIFAPI_FILE_SEARCH_CTX\fP fsearch"
The context for object search in key/policy store 
.SS "enum _FAPI_STATE_GET_RANDOM get_random_state"
The current state of get random 
.SS "TPMS_TIME_INFO init_time"
The current time during FAPI initialization\&. 
.SS "\fBIFAPI_Key_Sign\fP Key_Sign"
State information for key signing 
.SS "UINT32 nv_buffer_max"
The maximal size for transfer of nv buffer content 
.SS "\fBIFAPI_POLICY_CTX\fP policy"
The context of current policy\&. 
.SS "\fBESYS_TR\fP policy_session"
The policy session used by FAPI 
.br
 
.SS "enum _FAPI_STATE_PRIMARY primary_state"
The current state of the primary regeneration 
.SS "\fBESYS_TR\fP session1"
The first session used by FAPI 
.br
 
.SS "\fBESYS_TR\fP session2"
The second session used by FAPI 
.br
 
.SS "enum _FAPI_STATE_SESSION session_state"
The current state of the session creation 
.SS "enum _FAPI_STATE state"
The current state of the command execution 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
