.TH "Fapi_GetTcti" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fapi_GetTcti \- FAPI function to retrieve the TSS2_TCTI_CONTEXT currently used by the corresponding \fBFAPI_CONTEXT\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "TSS2_RC \fBFapi_GetTcti\fP (\fBFAPI_CONTEXT\fP *context, TSS2_TCTI_CONTEXT **tcti)"
.br
.in -1c
.SH "Detailed Description"
.PP 
FAPI function to retrieve the TSS2_TCTI_CONTEXT currently used by the corresponding \fBFAPI_CONTEXT\fP\&. 


.SH "Function Documentation"
.PP 
.SS "Fapi_GetTcti (\fBFAPI_CONTEXT\fP * context, TSS2_TCTI_CONTEXT ** tcti)"
One-Call function for Fapi_GetTcti
.PP
Fapi_GetTcti returns the TSS2_TCTI_CONTEXT currently used by the provided \fBFAPI_CONTEXT\fP\&. The purpose is to enable advanced access to the TPM that is currently being talked to\&. It is especially useful in combination with \fBFapi_GetTpmBlobs()\fP\&.
.PP
Note: The application must ensure that this TSS2_TCTI_CONTEXT is not being used in parallel to the processing of a FAPI command\&.
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP The \fBFAPI_CONTEXT\fP 
.br
\fItcti\fP The TSS2_TCTI_CONTEXT used to talk to the current TPM\&.
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP if the function call was a success\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP if context, tcti is NULL\&. 
.br
\fITSS2_FAPI_RC_BAD_CONTEXT\fP if context corruption is detected\&. 
.br
\fITSS2_FAPI_RC_NO_TPM\fP if FAPI was started in non-TPM mode\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
