.TH "FAPI_QUOTE_INFO" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FAPI_QUOTE_INFO
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fapi_int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "TPMT_SIG_SCHEME \fBsig_scheme\fP"
.br
.ti -1c
.RI "TPMS_ATTEST \fBattest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type for representing a external public key 
.SH "Field Documentation"
.PP 
.SS "TPMS_ATTEST attest"
Attestation data from Quote 
.SS "TPMT_SIG_SCHEME sig_scheme"
Signature scheme used for quote\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
