.TH "Fapi_VerifySignature" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fapi_VerifySignature \- FAPI functions to invoke VerifySignature either as one-call or in an asynchronous manner\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "TSS2_RC \fBFapi_VerifySignature\fP (\fBFAPI_CONTEXT\fP *context, char const *keyPath, uint8_t const *digest, size_t digestSize, uint8_t const *signature, size_t signatureSize)"
.br
.ti -1c
.RI "TSS2_RC \fBFapi_VerifySignature_Async\fP (\fBFAPI_CONTEXT\fP *context, char const *keyPath, uint8_t const *digest, size_t digestSize, uint8_t const *signature, size_t signatureSize)"
.br
.ti -1c
.RI "TSS2_RC \fBFapi_VerifySignature_Finish\fP (\fBFAPI_CONTEXT\fP *context)"
.br
.in -1c
.SH "Detailed Description"
.PP 
FAPI functions to invoke VerifySignature either as one-call or in an asynchronous manner\&. 


.SH "Function Documentation"
.PP 
.SS "Fapi_VerifySignature (\fBFAPI_CONTEXT\fP * context, char const * keyPath, uint8_t const * digest, size_t digestSize, uint8_t const * signature, size_t signatureSize)"
One-Call function for Fapi_VerifySignature
.PP
Verifies a signature using a public key found in a keyPath\&.
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP The \fBFAPI_CONTEXT\fP 
.br
\fIkeyPath\fP The path to the verification public key 
.br
\fIdigest\fP The that was signed\&. Must be already hashed 
.br
\fIdigestSize\fP the size of digest in bytes 
.br
\fIsignature\fP The signature to be verified 
.br
\fIsignatureSize\fP The size of signature in bytes
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP if the function call was a success\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP if context, keyPath, signature, or digest is NULL\&. 
.br
\fITSS2_FAPI_RC_BAD_CONTEXT\fP if context corruption is detected\&. 
.br
\fITSS2_FAPI_RC_KEY_NOT_FOUND\fP if keyPath does not map to a FAPI object\&. 
.br
\fITSS2_FAPI_RC_BAD_KEY\fP if the object at publicKeyPath is not a key, or is a key that is unsuitable for the requested operation\&. 
.br
\fITSS2_FAPI_RC_BAD_VALUE\fP if signature is invalid (has the wrong format) or if digestSize is zero\&. 
.br
\fITSS2_FAPI_RC_SIGNATURE_VERIFICATION_FAILED\fP if the signature fails to verify\&. 
.br
\fITSS2_FAPI_RC_BAD_SEQUENCE\fP if the context has an asynchronous operation already pending\&. 
.br
\fITSS2_FAPI_RC_IO_ERROR\fP if the data cannot be saved\&. 
.br
\fITSS2_FAPI_RC_MEMORY\fP if the FAPI cannot allocate enough memory for internal operations or return parameters\&. 
.br
\fITSS2_FAPI_RC_PATH_NOT_FOUND\fP if a FAPI object path was not found during authorization\&. 
.br
\fITSS2_FAPI_RC_TRY_AGAIN\fP if an I/O operation is not finished yet and this function needs to be called again\&. 
.br
\fITSS2_FAPI_RC_GENERAL_FAILURE\fP if an internal error occurred\&. 
.br
\fITSS2_FAPI_RC_NOT_PROVISIONED\fP FAPI was not provisioned\&. 
.br
\fITSS2_FAPI_RC_BAD_PATH\fP if the path is used in inappropriate context or contains illegal characters\&. 
.RE
.PP

.SS "Fapi_VerifySignature_Async (\fBFAPI_CONTEXT\fP * context, char const * keyPath, uint8_t const * digest, size_t digestSize, uint8_t const * signature, size_t signatureSize)"
Asynchronous function for Fapi_VerifySignature
.PP
Verifies a signature using a public key found in a keyPath\&.
.PP
Call Fapi_VerifySignature_Finish to finish the execution of this command\&.
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP The \fBFAPI_CONTEXT\fP 
.br
\fIkeyPath\fP The path to the verification public key 
.br
\fIdigest\fP The that was signed\&. Must be already hashed 
.br
\fIdigestSize\fP the size of digest in bytes 
.br
\fIsignature\fP The signature to be verified 
.br
\fIsignatureSize\fP The size of signature in bytes
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP if the function call was a success\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP if context, keyPath, signature, or digest is NULL\&. 
.br
\fITSS2_FAPI_RC_BAD_CONTEXT\fP if context corruption is detected\&. 
.br
\fITSS2_FAPI_RC_KEY_NOT_FOUND\fP if keyPath does not map to a FAPI object\&. 
.br
\fITSS2_FAPI_RC_BAD_KEY\fP if the object at publicKeyPath is not a key, or is a key that is unsuitable for the requested operation\&. 
.br
\fITSS2_FAPI_RC_BAD_VALUE\fP if signature is invalid (has the wrong format) or if digestSize is zero\&. 
.br
\fITSS2_FAPI_RC_SIGNATURE_VERIFICATION_FAILED\fP if the signature fails to verify\&. 
.br
\fITSS2_FAPI_RC_BAD_SEQUENCE\fP if the context has an asynchronous operation already pending\&. 
.br
\fITSS2_FAPI_RC_IO_ERROR\fP if the data cannot be saved\&. 
.br
\fITSS2_FAPI_RC_MEMORY\fP if the FAPI cannot allocate enough memory for internal operations or return parameters\&. 
.br
\fITSS2_FAPI_RC_PATH_NOT_FOUND\fP if a FAPI object path was not found during authorization\&. 
.br
\fITSS2_FAPI_RC_NOT_PROVISIONED\fP FAPI was not provisioned\&. 
.br
\fITSS2_FAPI_RC_BAD_PATH\fP if the path is used in inappropriate context or contains illegal characters\&. 
.RE
.PP

.SS "Fapi_VerifySignature_Finish (\fBFAPI_CONTEXT\fP * context)"
Asynchronous finish function for Fapi_VerifySignature
.PP
This function should be called after a previous Fapi_VerifySignature_Async\&.
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP The \fBFAPI_CONTEXT\fP
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP if the function call was a success\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP if context is NULL\&. 
.br
\fITSS2_FAPI_RC_BAD_CONTEXT\fP if context corruption is detected\&. 
.br
\fITSS2_FAPI_RC_BAD_SEQUENCE\fP if the context has an asynchronous operation already pending\&. 
.br
\fITSS2_FAPI_RC_IO_ERROR\fP if the data cannot be saved\&. 
.br
\fITSS2_FAPI_RC_MEMORY\fP if the FAPI cannot allocate enough memory for internal operations or return parameters\&. 
.br
\fITSS2_FAPI_RC_TRY_AGAIN\fP if the asynchronous operation is not yet complete\&. Call this function again later\&. 
.br
\fITSS2_FAPI_RC_GENERAL_FAILURE\fP if an internal error occurred\&. 
.br
\fITSS2_FAPI_RC_BAD_VALUE\fP if an invalid value was passed into the function\&. 
.br
\fITSS2_FAPI_RC_SIGNATURE_VERIFICATION_FAILED\fP if the signature could not be verified 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
