.TH "Fapi_Provision" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fapi_Provision \- FAPI functions to invoke Provision either as one-call or in an asynchronous manner\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "TSS2_RC \fBFapi_Provision\fP (\fBFAPI_CONTEXT\fP *context, char const *authValueEh, char const *authValueSh, char const *authValueLockout)"
.br
.ti -1c
.RI "TSS2_RC \fBFapi_Provision_Async\fP (\fBFAPI_CONTEXT\fP *context, char const *authValueEh, char const *authValueSh, char const *authValueLockout)"
.br
.ti -1c
.RI "TSS2_RC \fBFapi_Provision_Finish\fP (\fBFAPI_CONTEXT\fP *context)"
.br
.in -1c
.SH "Detailed Description"
.PP 
FAPI functions to invoke Provision either as one-call or in an asynchronous manner\&. 


.SH "Function Documentation"
.PP 
.SS "Fapi_Provision (\fBFAPI_CONTEXT\fP * context, char const * authValueEh, char const * authValueSh, char const * authValueLockout)"
One-Call function for the initial FAPI provisioning\&.
.PP
Provisions a TSS with its TPM\&. This includes the setting of important passwords and policy settings as well as the readout of the EK and its certificate and the initialization of the system-wide keystore\&.
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP The \fBFAPI_CONTEXT\fP\&. 
.br
\fIauthValueEh\fP The authorization value for the endorsement hierarchy\&. May be NULL 
.br
\fIauthValueSh\fP The authorization value for the storage hierarchy\&. Should be NULL 
.br
\fIauthValueLockout\fP The authorization value for lockout\&.
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP if the function call was a success\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP if context is NULL\&. 
.br
\fITSS2_FAPI_RC_BAD_CONTEXT\fP if context corruption is detected\&. 
.br
\fITSS2_FAPI_RC_BAD_SEQUENCE\fP if the context has an asynchronous operation already pending\&. 
.br
\fITSS2_FAPI_RC_NO_CERT\fP if no certificate was found for the computed EK\&. 
.br
\fITSS2_FAPI_RC_BAD_KEY\fP if public key of the EK does not match the configured certificate or the configured fingerprint does not match the computed EK\&. 
.br
\fITSS2_FAPI_RC_IO_ERROR\fP if the data cannot be saved\&. 
.br
\fITSS2_FAPI_RC_MEMORY\fP if the FAPI cannot allocate enough memory for internal operations or return parameters\&. 
.br
\fITSS2_FAPI_RC_NO_TPM\fP if FAPI was initialized in no-TPM-mode via its config file\&. 
.br
\fITSS2_FAPI_RC_TRY_AGAIN\fP if an I/O operation is not finished yet and this function needs to be called again\&. 
.br
\fITSS2_FAPI_RC_BAD_VALUE\fP if an invalid value was passed into the function\&. 
.br
\fITSS2_FAPI_RC_AUTHORIZATION_UNKNOWN\fP if a required authorization callback is not set\&. 
.br
\fITSS2_FAPI_RC_AUTHORIZATION_FAILED\fP if the authorization attempt fails\&. 
.br
\fITSS2_FAPI_RC_GENERAL_FAILURE\fP if an internal error occurred\&. 
.br
\fITSS2_FAPI_RC_POLICY_UNKNOWN\fP if policy search for a certain policy digest was not successful\&. 
.br
\fITSS2_FAPI_RC_PATH_NOT_FOUND\fP if a FAPI object path was not found during authorization\&. 
.br
\fITSS2_FAPI_RC_KEY_NOT_FOUND\fP if a key was not found\&. 
.br
\fITSS2_ESYS_RC_*\fP possible error codes of ESAPI\&. 
.br
\fITSS2_FAPI_RC_BAD_PATH\fP if the path is used in inappropriate context or contains illegal characters\&. 
.br
\fITSS2_FAPI_RC_NOT_PROVISIONED\fP FAPI was not provisioned\&. 
.br
\fITSS2_FAPI_RC_PATH_ALREADY_EXISTS\fP if the object already exists in object store\&. 
.RE
.PP

.SS "Fapi_Provision_Async (\fBFAPI_CONTEXT\fP * context, char const * authValueEh, char const * authValueSh, char const * authValueLockout)"
Asynchronous function for the initial FAPI provisioning\&.
.PP
Provisions a TSS with its TPM\&. This includes the setting of important passwords and policy settings as well as the readout of the EK and its certificate and the initialization of the system-wide keystore\&.
.PP
Call Fapi_Provision_Finish to finish the execution of this command\&.
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP The \fBFAPI_CONTEXT\fP\&. 
.br
\fIauthValueEh\fP The authorization value for the endorsement hierarchy\&. May be NULL 
.br
\fIauthValueSh\fP The authorization value for the storage hierarchy\&. Should be NULL 
.br
\fIauthValueLockout\fP The authorization value for lockout\&.
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP if the function call was a success\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP if context is NULL\&. 
.br
\fITSS2_FAPI_RC_BAD_CONTEXT\fP if context corruption is detected\&. 
.br
\fITSS2_FAPI_RC_BAD_SEQUENCE\fP if the context has an asynchronous operation already pending\&. 
.br
\fITSS2_FAPI_RC_IO_ERROR\fP if the data cannot be saved\&. 
.br
\fITSS2_FAPI_RC_MEMORY\fP if the FAPI cannot allocate enough memory for internal operations or return parameters\&. 
.br
\fITSS2_FAPI_RC_NO_TPM\fP if FAPI was initialized in no-TPM-mode via its config file\&. 
.br
\fITSS2_FAPI_RC_BAD_VALUE\fP if an invalid value was passed into the function\&. 
.br
\fITSS2_FAPI_RC_BAD_PATH\fP if the path is used in inappropriate context or contains illegal characters\&. 
.br
\fITSS2_FAPI_RC_PATH_NOT_FOUND\fP if a FAPI object path was not found during authorization\&. 
.RE
.PP

.SS "Fapi_Provision_Finish (\fBFAPI_CONTEXT\fP * context)"
Asynchronous finish function for Fapi_Provision
.PP
This function should be called after a previous Fapi_Provision_Async\&.
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP The \fBFAPI_CONTEXT\fP
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP if the function call was a success\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP if context is NULL\&. 
.br
\fITSS2_FAPI_RC_BAD_CONTEXT\fP if context corruption is detected\&. 
.br
\fITSS2_FAPI_RC_BAD_SEQUENCE\fP if the context has an asynchronous operation already pending\&. 
.br
\fITSS2_FAPI_RC_NO_CERT\fP if no certificate was found for the computed EK\&. 
.br
\fITSS2_FAPI_RC_BAD_KEY\fP if public key of the EK does not match the configured certificate or the configured fingerprint does not match the computed EK\&. 
.br
\fITSS2_FAPI_RC_IO_ERROR\fP if the data cannot be saved\&. 
.br
\fITSS2_FAPI_RC_MEMORY\fP if the FAPI cannot allocate enough memory for internal operations or return parameters\&. 
.br
\fITSS2_FAPI_RC_TRY_AGAIN\fP if the asynchronous operation is not yet complete\&. Call this function again later\&. 
.br
\fITSS2_FAPI_RC_BAD_VALUE\fP if an invalid value was passed into the function\&. 
.br
\fITSS2_FAPI_RC_AUTHORIZATION_UNKNOWN\fP if a required authorization callback is not set\&. 
.br
\fITSS2_FAPI_RC_AUTHORIZATION_FAILED\fP if the authorization attempt fails\&. 
.br
\fITSS2_FAPI_RC_GENERAL_FAILURE\fP if an internal error occurred\&. 
.br
\fITSS2_FAPI_RC_POLICY_UNKNOWN\fP if policy search for a certain policy digest was not successful\&. 
.br
\fITSS2_FAPI_RC_PATH_NOT_FOUND\fP if a FAPI object path was not found during authorization\&. 
.br
\fITSS2_FAPI_RC_KEY_NOT_FOUND\fP if a key was not found\&. 
.br
\fITSS2_ESYS_RC_*\fP possible error codes of ESAPI\&. 
.br
\fITSS2_FAPI_RC_NOT_PROVISIONED\fP FAPI was not provisioned\&. 
.br
\fITSS2_FAPI_RC_BAD_PATH\fP if the path is used in inappropriate context or contains illegal characters\&. 
.br
\fITSS2_FAPI_RC_PATH_ALREADY_EXISTS\fP if the object already exists in object store\&. 
.RE
.PP
< Certificates will be stored at even address
.PP
< RSA template
.PP
< ECC template
.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
