.TH "iesys_crypto" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iesys_crypto
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "TSS2_RC \fBiesys_crypto_hash_get_digest_size\fP (TPM2_ALG_ID hashAlg, size_t *size)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The types and functions used internally by ESAPI for cryptographic operations\&. Multiple implementations of these functions may exist for different cryptographic backends\&. 
.SH "Function Documentation"
.PP 
.SS "TSS2_RC iesys_crypto_hash_get_digest_size (TPM2_ALG_ID hashAlg, size_t * size)"
Provide the digest size for a given hash algorithm\&.
.PP
This function provides the size of the digest for a given hash algorithm\&.
.PP
\fBParameters\fP
.RS 4
\fIhashAlg\fP The hash algorithm to get the size for\&. 
.br
\fIsize\fP The side of a digest of the hash algorithm\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP on success\&. 
.br
\fITSS2_ESYS_RC_BAD_VALUE\fP if hashAlg is unknown or unsupported\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
