.TH "IFAPI_CreatePrimary" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_CreatePrimary
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fapi_int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP \fBhierarchy\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP \fBpkey_object\fP"
.br
.ti -1c
.RI "TPM2B_SENSITIVE_CREATE \fBinSensitive\fP"
.br
.ti -1c
.RI "TPM2B_DATA \fBoutsideInfo\fP"
.br
.ti -1c
.RI "TPML_PCR_SELECTION \fBcreationPCR\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBhandle\fP"
.br
.ti -1c
.RI "TPMI_DH_PERSISTENT \fBpersistent_handle\fP"
.br
.ti -1c
.RI "TPMS_CAPABILITY_DATA * \fBcapabilityData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The data structure holding internal state of regenerate primary key\&. 
.SH "Field Documentation"
.PP 
.SS "\fBIFAPI_OBJECT\fP hierarchy"
The current used hierarchy for CreatePrimary 
.SS "char* path"
Path of the primary (starting with hierarchy) 
.br
 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
