.TH "IFAPI_PROFILE" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_PROFILE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_profiles\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "TPMI_ALG_PUBLIC \fBtype\fP"
.br
.ti -1c
.RI "char * \fBsrk_template\fP"
.br
.ti -1c
.RI "char * \fBek_template\fP"
.br
.ti -1c
.RI "char * \fBsrk_description\fP"
.br
.ti -1c
.RI "char * \fBek_description\fP"
.br
.ti -1c
.RI "TPMT_SIG_SCHEME \fBecc_signing_scheme\fP"
.br
.ti -1c
.RI "TPMT_SIG_SCHEME \fBrsa_signing_scheme\fP"
.br
.ti -1c
.RI "TPMT_RSA_DECRYPT \fBrsa_decrypt_scheme\fP"
.br
.ti -1c
.RI "TPMI_ALG_CIPHER_MODE \fBsym_mode\fP"
.br
.ti -1c
.RI "TPMT_SYM_DEF_OBJECT \fBsym_parameters\fP"
.br
.ti -1c
.RI "UINT16 \fBsym_block_size\fP"
.br
.ti -1c
.RI "TPML_PCR_SELECTION \fBpcr_selection\fP"
.br
.ti -1c
.RI "TPMI_ALG_HASH \fBnameAlg\fP"
.br
.ti -1c
.RI "TPMI_RSA_KEY_BITS \fBkeyBits\fP"
.br
.ti -1c
.RI "UINT32 \fBexponent\fP"
.br
.ti -1c
.RI "TPMI_ECC_CURVE \fBcurveID\fP"
.br
.ti -1c
.RI "TPMT_SYM_DEF \fBsession_symmetric\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICY\fP * \fBeh_policy\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICY\fP * \fBsh_policy\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICY\fP * \fBek_policy\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICY\fP * \fBsrk_policy\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICY\fP * \fBlockout_policy\fP"
.br
.ti -1c
.RI "UINT32 \fBnewMaxTries\fP"
.br
.ti -1c
.RI "UINT32 \fBnewRecoveryTime\fP"
.br
.ti -1c
.RI "UINT32 \fBlockoutRecovery\fP"
.br
.ti -1c
.RI "TPMI_YES_NO \fBignore_ek_template\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal structure for FAPI profiles 
.SH "Field Documentation"
.PP 
.SS "TPMT_SIG_SCHEME ecc_signing_scheme"
Signing scheme for the ECC key\&. 
.SS "char* ek_description"
EK description 
.SS "char* ek_template"
EK template 
.SS "TPML_PCR_SELECTION pcr_selection"
Parameters for symmectric encryption\&. 
.SS "TPMT_RSA_DECRYPT rsa_decrypt_scheme"
Decrypt scheme for the RSA key\&. 
.SS "TPMT_SIG_SCHEME rsa_signing_scheme"
Signing scheme for the RSA key\&. 
.SS "char* srk_description"
SRK description 
.SS "char* srk_template"
SRK template 
.SS "UINT16 sym_block_size"
Block size for symmectric encryption\&. 
.SS "TPMI_ALG_CIPHER_MODE sym_mode"
Mode for symmectric encryption\&. 
.SS "TPMT_SYM_DEF_OBJECT sym_parameters"
Parameters for symmectric encryption\&. 
.SS "TPMI_ALG_PUBLIC type"
The algorithm used for key creation 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
