.TH "IFAPI_POLICY_EXEC_CTX" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_POLICY_EXEC_CTX
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_policy_execute\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum IFAPI_STATE_POLICY_EXCECUTE \fBstate\fP"
.br
.ti -1c
.RI "TPML_DIGEST \fBdigest_list\fP"
.br
.ti -1c
.RI "\fBIFAPI_POLICY_EXEC_CTX\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBIFAPI_POLICY_EXEC_CTX\fP * \fBprev\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBsession\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICY\fP * \fBpolicy\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBpolicySessionSav\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBobject_handle\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBnv_index\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBauth_handle\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP \fBauth_objectNV\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP * \fBauth_object\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBauth_session\fP"
.br
.ti -1c
.RI "TPMI_ALG_HASH \fBhash_alg\fP"
.br
.ti -1c
.RI "void * \fBapp_data\fP"
.br
.ti -1c
.RI "\fBNODE_OBJECT_T\fP * \fBpolicy_elements\fP"
.br
.ti -1c
.RI "TPM2B_DIGEST * \fBnonceTPM\fP"
.br
.ti -1c
.RI "uint8_t * \fBbuffer\fP"
.br
.ti -1c
.RI "size_t \fBbuffer_size\fP"
.br
.ti -1c
.RI "TPM2B_NAME \fBname\fP"
.br
.ti -1c
.RI "char * \fBpem_key\fP"
.br
.ti -1c
.RI "struct \fBPOLICY_LIST\fP * \fBpolicy_list\fP"
.br
.ti -1c
.RI "bool \fBflush_handle\fP"
.br
.ti -1c
.RI "TSS2_POLICY_EXEC_CALLBACKS \fBcallbacks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The context of the policy execution 
.SH "Field Documentation"
.PP 
.SS "void* app_data"
Application data for policy execution callbacks 
.SS "\fBIFAPI_OBJECT\fP* auth_object"
Object to be authorized 
.SS "\fBIFAPI_OBJECT\fP auth_objectNV"
Object used for NV authentication 
.SS "TSS2_POLICY_EXEC_CALLBACKS callbacks"
callbacks used for execution of sub policies and actions which require access to the FAPI context\&. 
.SS "bool flush_handle"
Handle to be flushed after policy execution 
.SS "\fBIFAPI_POLICY_EXEC_CTX\fP* next"
The digest list of policy or Pointer to next policy 
.SS "char* pem_key"
Pem key recreated during policy execution 
.SS "\fBNODE_OBJECT_T\fP* policy_elements"
The policy elements to be executed 
.SS "struct \fBPOLICY_LIST\fP* policy_list"
List of policies for authorization selection 
.SS "\fBESYS_TR\fP policySessionSav"
Backup policy session 
.SS "\fBIFAPI_POLICY_EXEC_CTX\fP* prev"
Pointer to previous policy 
.SS "\fBESYS_TR\fP session"
The current policy session 
.SS "enum IFAPI_STATE_POLICY_EXCECUTE state"
The execution state of the current policy command 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
