.TH "IFAPI_IMA_TEMPLATE" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_IMA_TEMPLATE
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   UINT32 \fBpcr\fP"
.br
.ti -1c
.RI "   UINT8 \fBdigest\fP [TPM2_SHA512_DIGEST_SIZE+sizeof(UINT32)+3]"
.br
.ti -1c
.RI "} \fBheader\fP"
.br
.ti -1c
.RI "UINT32 \fBima_type_size\fP"
.br
.ti -1c
.RI "size_t \fBhash_size\fP"
.br
.ti -1c
.RI "TPMI_ALG_HASH \fBhash_alg\fP"
.br
.ti -1c
.RI "char \fBima_type\fP [TCG_EVENT_NAME_LEN_MAX+1]"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "UINT32 \fBevent_size\fP"
.br
.ti -1c
.RI "UINT8 * \fBevent_buffer\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "UINT8* event_buffer"
The data after header and name 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
