.TH "IFAPI_Key_VerifySignature" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_Key_VerifySignature
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fapi_int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBkeyPath\fP"
.br
.ti -1c
.RI "const uint8_t * \fBsignature\fP"
.br
.ti -1c
.RI "size_t \fBsignatureSize\fP"
.br
.ti -1c
.RI "const uint8_t * \fBdigest\fP"
.br
.ti -1c
.RI "size_t \fBdigestSize\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP \fBkey_object\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The data structure holding internal state of key verify signature\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
