.TH "IFAPI_EVENTLOG" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_EVENTLOG
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum IFAPI_EVENTLOG_STATE \fBstate\fP"
.br
.ti -1c
.RI "char * \fBlog_dir\fP"
.br
.ti -1c
.RI "const char * \fBfirmware_log_file\fP"
.br
.ti -1c
.RI "const char * \fBima_log_file\fP"
.br
.ti -1c
.RI "struct \fBIFAPI_EVENT\fP \fBevent\fP"
.br
.ti -1c
.RI "TPM2_HANDLE \fBpcrList\fP [TPM2_MAX_PCRS]"
.br
.ti -1c
.RI "size_t \fBpcrListSize\fP"
.br
.ti -1c
.RI "size_t \fBpcrListIdx\fP"
.br
.ti -1c
.RI "json_object * \fBlog\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
