.TH "IFAPI_Entities_List" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_Entities_List
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fapi_int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBsearchPath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The data structure holding internal state of list entities\&. 
.SH "Field Documentation"
.PP 
.SS "const char* searchPath"
The path to searched for objectws 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
