.TH "IFAPI_INITIALIZE" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_INITIALIZE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fapi_int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "TPMS_CAPABILITY_DATA * \fBcapability\fP"
.br
.ti -1c
.RI "char ** \fBpathlist\fP"
.br
.ti -1c
.RI "size_t \fBnumPaths\fP"
.br
.ti -1c
.RI "size_t \fBnumNullPrimaries\fP"
.br
.ti -1c
.RI "size_t \fBprimary_idx\fP"
.br
.ti -1c
.RI "size_t \fBpath_idx\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP * \fBnull_primaries\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The data structure holding internal state of Fapi_Initialize command\&. 
.SH "Field Documentation"
.PP 
.SS "\fBIFAPI_OBJECT\fP* null_primaries"
Array of the NULL hierarchy primaries\&. 
.SS "size_t numNullPrimaries"
Number of NULL hierarchy primaries stored in keystore 
.SS "size_t numPaths"
Size of array with all keystore objects 
.SS "size_t path_idx"
Index of array with the object paths 
.SS "char** pathlist"
The array with all keystore objects 
.SS "size_t primary_idx"
Index to the current primary 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
