.TH "ifapi_policy_intantiate" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ifapi_policy_intantiate
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "TSS2_RC \fBifapi_policyeval_instantiate_finish\fP (\fBIFAPI_POLICY_EVAL_INST_CTX\fP *context)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides functions for instantiation of the policies\&. The defaults will be initialized according to the given values\&. 
.SH "Function Documentation"
.PP 
.SS "TSS2_RC ifapi_policyeval_instantiate_finish (\fBIFAPI_POLICY_EVAL_INST_CTX\fP * context)"
Finalize instantiation a policy template\&.
.PP
All needed asynchronous callbacks will be executed for all policy elements offset The policy\&.
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP The context storing information for re-entry after try again\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP on success\&. 
.br
\fITSS2_FAPI_RC_BAD_TEMPLATE\fP If the template is not complete for instantiation\&. 
.br
\fIFAPI\fP error codes on failure 
.br
\fITSS2_FAPI_RC_TRY_AGAIN\fP if an I/O operation is not finished yet and this function needs to be called again\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP a invalid null pointer is passed\&. 
.br
\fITSS2_FAPI_RC_MEMORY\fP if not enough memory can be allocated\&. 
.br
\fITSS2_FAPI_RC_BAD_VALUE\fP if an invalid value was passed into the function\&. 
.br
\fITSS2_FAPI_RC_GENERAL_FAILURE\fP if an internal error occurred\&. 
.br
\fITSS2_FAPI_RC_BAD_SEQUENCE\fP if the context has an asynchronous operation already pending\&. 
.br
\fITSS2_FAPI_RC_PATH_NOT_FOUND\fP if a FAPI object path was not found during authorization\&. 
.br
\fITSS2_FAPI_RC_KEY_NOT_FOUND\fP if a key was not found\&. 
.br
\fITSS2_FAPI_RC_IO_ERROR\fP if an error occurred while accessing the object store\&. 
.br
\fITSS2_ESYS_RC_*\fP possible error codes of ESAPI\&. 
.br
\fITSS2_FAPI_RC_NOT_PROVISIONED\fP FAPI was not provisioned\&. 
.br
\fITSS2_FAPI_RC_BAD_PATH\fP if the path is used in inappropriate context or contains illegal characters\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
