.TH "IFAPI_POLICY_EXEC_CB_CTX" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_POLICY_EXEC_CB_CTX
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_policy_callbacks\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum IFAPI_STATE_POL_CB_EXCECUTE \fBcb_state\fP"
.br
.ti -1c
.RI "char * \fBobject_path\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP \fBobject\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBkey_handle\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBnv_index\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBauth_index\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBflush_handle\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP \fBauth_object\fP"
.br
.ti -1c
.RI "\fBIFAPI_LoadKey\fP \fBload_ctx_sav\fP"
.br
.ti -1c
.RI "\fBIFAPI_LoadKey\fP \fBload_ctx\fP"
.br
.ti -1c
.RI "\fBIFAPI_CreatePrimary\fP \fBcreate_primary_ctx_sav\fP"
.br
.ti -1c
.RI "\fBIFAPI_CreatePrimary\fP \fBcreate_primary_ctx\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP * \fBkey_object_ptr\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP * \fBauth_object_ptr\fP"
.br
.ti -1c
.RI "\fBIFAPI_NV_Cmds\fP \fBnv_cmd_state\fP"
.br
.ti -1c
.RI "\fBIFAPI_NV_Cmds\fP \fBnv_cmd_state_sav\fP"
.br
.ti -1c
.RI "TPM2B_DIGEST \fBpolicy_digest\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBsession\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICY\fP * \fBpolicy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The context of the policy execution 
.SH "Field Documentation"
.PP 
.SS "\fBESYS_TR\fP auth_index"
Index of authorization object 
.SS "\fBIFAPI_OBJECT\fP auth_object"
FAPI auth object needed for authorization 
.SS "enum IFAPI_STATE_POL_CB_EXCECUTE cb_state"
The execution state of the current policy callback 
.SS "\fBESYS_TR\fP flush_handle"
Handle which has to be flushed after policy execution 
.SS "\fBESYS_TR\fP key_handle"
Handle of a used key 
.SS "\fBIFAPI_NV_Cmds\fP nv_cmd_state_sav"
backup for state of fapi nv commands 
.SS "\fBESYS_TR\fP nv_index"
Index of nv object storing a policy 
.SS "\fBIFAPI_OBJECT\fP object"
Object to be authorized 
.SS "char* object_path"
The pathname determined by object search 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
