.TH "IFAPI_GetEsysBlob" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_GetEsysBlob
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fapi_int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.ti -1c
.RI "uint8_t * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBlength\fP"
.br
.ti -1c
.RI "bool \fBis_key\fP"
.br
.ti -1c
.RI "bool \fBis_persistent_key\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBnew_object_handle\fP"
.br
.ti -1c
.RI "TPM2_HANDLE \fBpermanentHandle\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP \fBauth_object\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBauth_index\fP"
.br
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP \fBobject\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP * \fBkey_object\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The data structure holding internal state of esys get blob\&. 
.SH "Field Documentation"
.PP 
.SS "\fBESYS_TR\fP auth_index"
The ESAPI handle of the nv authorization object 
.SS "\fBIFAPI_OBJECT\fP auth_object"
Object used for authentication 
.SS "uint8_t* data"
data of the blob to be returned 
.SS "bool is_key"
Object is a key 
.SS "bool is_persistent_key"
Object is a persistent key 
.SS "\fBIFAPI_OBJECT\fP* key_object"
Loaded key object 
.SS "size_t length"
The size of the data to be returned 
.SS "\fBIFAPI_OBJECT\fP object"
Deserialized object 
.SS "char* path"
The path of the object 
.SS "TPM2_HANDLE permanentHandle"
The TPM permanent handle 
.SS "uint8_t type"
type of blob to be returned 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
