.TH "ifapi_eventlog" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ifapi_eventlog
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBifapi_cleanup_event\fP (\fBIFAPI_EVENT\fP *event)"
.br
.ti -1c
.RI "TSS2_RC \fBifapi_eventlog_append_check\fP (\fBIFAPI_EVENTLOG\fP *eventlog, \fBIFAPI_IO\fP *io)"
.br
.ti -1c
.RI "TSS2_RC \fBifapi_eventlog_append_finish\fP (\fBIFAPI_EVENTLOG\fP *eventlog, \fBIFAPI_IO\fP *io, const \fBIFAPI_EVENT\fP *pcr_event)"
.br
.ti -1c
.RI "TSS2_RC \fBifapi_eventlog_get_async\fP (\fBIFAPI_EVENTLOG\fP *eventlog, \fBIFAPI_IO\fP *io, const TPM2_HANDLE *pcrList, size_t pcrListSize)"
.br
.ti -1c
.RI "TSS2_RC \fBifapi_eventlog_get_finish\fP (\fBIFAPI_EVENTLOG\fP *eventlog, \fBIFAPI_IO\fP *io, char **log)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides internal fapi functions for the handling of event logs 
.SH "Function Documentation"
.PP 
.SS "void ifapi_cleanup_event (\fBIFAPI_EVENT\fP * event)"
Free allocated memory for an ifapi event\&.
.PP
\fBParameters\fP
.RS 4
\fIevent\fP The structure to be cleaned up\&. 
.RE
.PP

.SS "TSS2_RC ifapi_eventlog_append_check (\fBIFAPI_EVENTLOG\fP * eventlog, \fBIFAPI_IO\fP * io)"
Check event log format before appending an event to the existing event log\&.
.PP
Call after ifapi_eventlog_get_async\&.
.PP
\fBParameters\fP
.RS 4
\fIeventlog\fP The context area for the eventlog\&. 
.br
\fIio\fP The context area for the asynchronous io module\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP on success\&. 
.br
\fITSS2_FAPI_RC_IO_ERROR\fP if creation of log_dir failed or log_dir is not writable\&. 
.br
\fITSS2_FAPI_RC_MEMORY\fP if memory allocation failed\&. 
.br
\fITSS2_FAPI_RC_TRY_AGAIN\fP if the I/O operation is not finished yet and this function needs to be called again\&. 
.br
\fITSS2_FAPI_RC_BAD_VALUE\fP if an invalid value was passed into the function\&. 
.br
\fITSS2_FAPI_RC_GENERAL_FAILURE\fP if an internal error occurred\&. 
.br
\fITSS2_FAPI_RC_BAD_SEQUENCE\fP if the context has an asynchronous operation already pending\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP a invalid null pointer is passed\&. 
.RE
.PP

.SS "TSS2_RC ifapi_eventlog_append_finish (\fBIFAPI_EVENTLOG\fP * eventlog, \fBIFAPI_IO\fP * io, const \fBIFAPI_EVENT\fP * pcr_event)"
Append an event to the existing event log\&.
.PP
Call after ifapi_eventlog_get_async\&.
.PP
\fBParameters\fP
.RS 4
\fIeventlog\fP The context area for the eventlog\&. 
.br
\fIio\fP The context area for the asynchronous io module\&. 
.br
\fIpcr_event\fP The event to be appended to the eventlog\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP on success\&. 
.br
\fITSS2_FAPI_RC_IO_ERROR\fP if creation of log_dir failed or log_dir is not writable\&. 
.br
\fITSS2_FAPI_RC_MEMORY\fP if memory allocation failed\&. 
.br
\fITSS2_FAPI_RC_TRY_AGAIN\fP if the I/O operation is not finished yet and this function needs to be called again\&. 
.br
\fITSS2_FAPI_RC_BAD_VALUE\fP if an invalid value was passed into the function\&. 
.br
\fITSS2_FAPI_RC_GENERAL_FAILURE\fP if an internal error occurred\&. 
.br
\fITSS2_FAPI_RC_BAD_SEQUENCE\fP if the context has an asynchronous operation already pending\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP a invalid null pointer is passed\&. 
.RE
.PP

.SS "TSS2_RC ifapi_eventlog_get_async (\fBIFAPI_EVENTLOG\fP * eventlog, \fBIFAPI_IO\fP * io, const TPM2_HANDLE * pcrList, size_t pcrListSize)"
Retrieve the eventlog for a given list of pcrs using asynchronous io\&.
.PP
Call ifapi_eventlog_get_finish to retrieve the results\&.
.PP
\fBParameters\fP
.RS 4
\fIeventlog\fP The context area for the eventlog\&. 
.br
\fIio\fP The context area for the asynchronous io module\&. 
.br
\fIpcrList\fP The list of PCR indices to retrieve the log for\&. 
.br
\fIpcrListSize\fP The size of pcrList\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP on success\&. 
.br
\fITSS2_FAPI_RC_IO_ERROR\fP if creation of log_dir failed or log_dir is not writable\&. 
.br
\fITSS2_FAPI_RC_MEMORY\fP if memory allocation failed\&. 
.br
\fITSS2_FAPI_RC_BAD_VALUE\fP if an invalid value was passed into the function\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP a invalid null pointer is passed\&. 
.RE
.PP

.SS "TSS2_RC ifapi_eventlog_get_finish (\fBIFAPI_EVENTLOG\fP * eventlog, \fBIFAPI_IO\fP * io, char ** log)"
Retrieve the eventlog for a given list of pcrs using asynchronous io\&.
.PP
Call after ifapi_eventlog_get_async\&.
.PP
\fBParameters\fP
.RS 4
\fIeventlog\fP The context area for the eventlog\&. 
.br
\fIio\fP The context area for the asynchronous io module\&. 
.br
\fIlog\fP The event log for the requested PCRs in JSON format 
.RE
.PP
\fBReturn values\fP
.RS 4
\fITSS2_RC_SUCCESS\fP on success\&. 
.br
\fITSS2_FAPI_RC_IO_ERROR\fP if creation of log_dir failed or log_dir is not writable\&. 
.br
\fITSS2_FAPI_RC_MEMORY\fP if memory allocation failed\&. 
.br
\fITSS2_FAPI_RC_TRY_AGAIN\fP if the I/O operation is not finished yet and this function needs to be called again\&. 
.br
\fITSS2_FAPI_RC_BAD_VALUE\fP if an invalid value was passed into the function\&. 
.br
\fITSS2_FAPI_RC_BAD_SEQUENCE\fP if the context has an asynchronous operation already pending\&. 
.br
\fITSS2_FAPI_RC_BAD_REFERENCE\fP a invalid null pointer is passed\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
