.TH "IFAPI_INFO_CAP" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_INFO_CAP
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBdescription\fP"
.br
.ti -1c
.RI "TPMI_POLICYTYPE \fBcapability\fP"
.br
.ti -1c
.RI "UINT32 \fBproperty\fP"
.br
.ti -1c
.RI "UINT32 \fBmax\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
