.TH "IFAPI_KEYSTORE" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_KEYSTORE
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBsystemdir\fP"
.br
.ti -1c
.RI "char * \fBuserdir\fP"
.br
.ti -1c
.RI "char * \fBdefaultprofile\fP"
.br
.ti -1c
.RI "\fBIFAPI_KEY_SEARCH\fP \fBkey_search\fP"
.br
.ti -1c
.RI "const char * \fBrel_path\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
