.TH "IFAPI_PROFILES" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_PROFILES
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBdefault_name\fP"
.br
.ti -1c
.RI "struct \fBIFAPI_PROFILE\fP \fBdefault_profile\fP"
.br
.ti -1c
.RI "struct \fBIFAPI_PROFILE_ENTRY\fP * \fBprofiles\fP"
.br
.ti -1c
.RI "char ** \fBfilenames\fP"
.br
.ti -1c
.RI "size_t \fBnum_profiles\fP"
.br
.ti -1c
.RI "size_t \fBprofiles_idx\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
