.TH "IFAPI_NV" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_NV
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_keystore\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "TPM2B_NV_PUBLIC \fBpublic\fP"
.br
.ti -1c
.RI "\fBUINT8_ARY\fP \fBserialization\fP"
.br
.ti -1c
.RI "UINT32 \fBhierarchy\fP"
.br
.ti -1c
.RI "char * \fBpolicyInstance\fP"
.br
.ti -1c
.RI "char * \fBdescription\fP"
.br
.ti -1c
.RI "\fBUINT8_ARY\fP \fBappData\fP"
.br
.ti -1c
.RI "TPMI_YES_NO \fBwith_auth\fP"
.br
.ti -1c
.RI "char * \fBevent_log\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type for representing a FAPI NV object 
.SH "Field Documentation"
.PP 
.SS "\fBUINT8_ARY\fP appData"
Application data 
.SS "char* description"
Human readable description of key 
.SS "char* event_log"
The event log if NV type is pcr 
.SS "UINT32 hierarchy"
The hierarchy used for NV object creation 
.SS "char* policyInstance"
Keys policy 
.SS "TPM2B_NV_PUBLIC public"
The wrapped public portion of the object 
.SS "\fBUINT8_ARY\fP serialization"
None 
.SS "TPMI_YES_NO with_auth"
Authorization provided during creation 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
