.TH "IFAPI_ExportPolicy" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_ExportPolicy
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fapi_int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBpath\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP \fBobject\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICY\fP \fBpolicy\fP"
.br
.ti -1c
.RI "TPMI_ALG_HASH \fBhashAlg\fP"
.br
.ti -1c
.RI "size_t \fBprofile_idx\fP"
.br
.ti -1c
.RI "bool \fBcompute_policy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The data structure holding internal state of export policy\&. 
.SH "Field Documentation"
.PP 
.SS "bool compute_policy"
Switch whether computation of the policy for the default name hash alg is needed\&. 
.SS "TPMI_ALG_HASH hashAlg"
Index of profile used for digest computation\&. 
.SS "\fBIFAPI_OBJECT\fP object"
Object corresponding to path 
.SS "const char* path"
Path of the object with the policy to be exported 
.SS "\fBTPMS_POLICY\fP policy"
Policy from store be exported 
.SS "size_t profile_idx"
hashAlg used for policy digest computation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
