.TH "IFAPI_PROFILE_ENTRY" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_PROFILE_ENTRY
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "struct \fBIFAPI_PROFILE\fP \fBprofile\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* name"
Name of a profile 
.SS "struct \fBIFAPI_PROFILE\fP profile"
Values for a profile 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
