.TH "IFAPI_ImportKey" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_ImportKey
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fapi_int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBIFAPI_OBJECT\fP \fBobject\fP"
.br
.ti -1c
.RI "TPM2B_NAME \fBparent_name\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP * \fBparent_object\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP \fBnew_object\fP"
.br
.ti -1c
.RI "char * \fBparent_path\fP"
.br
.ti -1c
.RI "char * \fBout_path\fP"
.br
.ti -1c
.RI "TPM2B_PRIVATE * \fBprivate\fP"
.br
.ti -1c
.RI "char * \fBjso_string\fP"
.br
.ti -1c
.RI "const \fBIFAPI_PROFILE\fP * \fBprofile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The data structure holding internal state of import key\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
