.TH "IFAPI_PCR" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_PCR
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fapi_int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "TPML_DIGEST_VALUES \fBdigest_list\fP"
.br
.ti -1c
.RI "TPML_DIGEST_VALUES * \fBevent_digests\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBPCR\fP"
.br
.ti -1c
.RI "TPML_PCR_SELECTION \fBpcr_selection\fP"
.br
.ti -1c
.RI "TPML_PCR_SELECTION * \fBpcr_selection_out\fP"
.br
.ti -1c
.RI "UINT32 \fBupdate_count\fP"
.br
.ti -1c
.RI "TPML_DIGEST * \fBpcrValues\fP"
.br
.ti -1c
.RI "TPM2_HANDLE \fBpcrIndex\fP"
.br
.ti -1c
.RI "TPMI_ALG_HASH \fBhashAlg\fP"
.br
.ti -1c
.RI "const char * \fBkeyPath\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBhandle\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP * \fBkey_object\fP"
.br
.ti -1c
.RI "TPMS_CAPABILITY_DATA * \fBcapabilityData\fP"
.br
.ti -1c
.RI "uint32_t * \fBpcrList\fP"
.br
.ti -1c
.RI "size_t \fBpcrListSize\fP"
.br
.ti -1c
.RI "TPM2B_DATA \fBqualifyingData\fP"
.br
.ti -1c
.RI "const uint8_t * \fBeventData\fP"
.br
.ti -1c
.RI "TPM2B_EVENT \fBevent\fP"
.br
.ti -1c
.RI "size_t \fBeventDataSize\fP"
.br
.ti -1c
.RI "const uint32_t * \fBhashAlgs\fP"
.br
.ti -1c
.RI "uint32_t * \fBhashAlgs2\fP"
.br
.ti -1c
.RI "size_t \fBnumHashAlgs\fP"
.br
.ti -1c
.RI "const char * \fBquoteInfo\fP"
.br
.ti -1c
.RI "TPM2B_ATTEST * \fBtpm_quoted\fP"
.br
.ti -1c
.RI "TPMT_SIGNATURE * \fBtpm_signature\fP"
.br
.ti -1c
.RI "uint8_t * \fBsignature\fP"
.br
.ti -1c
.RI "size_t \fBsignatureSize\fP"
.br
.ti -1c
.RI "const char * \fBlogData\fP"
.br
.ti -1c
.RI "char * \fBpcrLog\fP"
.br
.ti -1c
.RI "\fBIFAPI_EVENT\fP \fBpcr_event\fP"
.br
.ti -1c
.RI "json_object * \fBevent_list\fP"
.br
.ti -1c
.RI "\fBFAPI_QUOTE_INFO\fP \fBfapi_quote_info\fP"
.br
.ti -1c
.RI "uint8_t * \fBpcrValue\fP"
.br
.ti -1c
.RI "size_t \fBpcrValueSize\fP"
.br
.ti -1c
.RI "char * \fBevent_log_file\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The data structure holding internal state of Fapi_PCR commands\&. 
.SH "Field Documentation"
.PP 
.SS "TPML_DIGEST_VALUES digest_list"
The digest list computed for the event 
.br
 
.SS "TPML_DIGEST_VALUES* event_digests"
The digest list computed by TPM2_Event 
.br
 
.SS "\fBESYS_TR\fP handle"
The ESYS handle of the signing key 
.SS "\fBIFAPI_OBJECT\fP* key_object"
The IPAPI object of the signing key 
.SS "const char* keyPath"
The implicit key path for PCR_Quote 
.SS "\fBESYS_TR\fP PCR"
The handle of the PCR register to be extended 
.SS "TPML_PCR_SELECTION pcr_selection"
Selection used for Read and Quote 
.SS "TPML_PCR_SELECTION* pcr_selection_out"
Selection returned by PCR_Read 
.br
 
.SS "uint32_t* pcrList"
Array of PCR numbers 
.SS "size_t pcrListSize"
Size of PCR array 
.SS "TPM2B_DATA qualifyingData"
Nonce for quote command 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
