.TH "IFAPI_MAX_BUFFER" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_MAX_BUFFER
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "UINT16 \fBsize\fP"
.br
.ti -1c
.RI "BYTE \fBbuffer\fP [IFAPI_MAX_BUFFER_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
