.TH "IFAPI_CONFIG" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_CONFIG
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_config\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBprofile_dir\fP"
.br
.ti -1c
.RI "char * \fBuser_dir\fP"
.br
.ti -1c
.RI "char * \fBkeystore_dir\fP"
.br
.ti -1c
.RI "char * \fBprofile_name\fP"
.br
.ti -1c
.RI "char * \fBtcti\fP"
.br
.ti -1c
.RI "char * \fBlog_dir\fP"
.br
.ti -1c
.RI "TPML_PCR_SELECTION \fBsystem_pcrs\fP"
.br
.ti -1c
.RI "TPMT_HA \fBek_fingerprint\fP"
.br
.ti -1c
.RI "char * \fBek_cert_file\fP"
.br
.ti -1c
.RI "TPMI_YES_NO \fBek_cert_less\fP"
.br
.ti -1c
.RI "char * \fBintel_cert_service\fP"
.br
.ti -1c
.RI "char * \fBfirmware_log_file\fP"
.br
.ti -1c
.RI "char * \fBima_log_file\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type for storing FAPI configuration 
.SH "Field Documentation"
.PP 
.SS "TPMT_HA ek_fingerprint"
Fingerprint of EK 
.SS "char* intel_cert_service"
Certificate service for Intel TPMs 
.SS "char* keystore_dir"
Directory storing key and NV objects 
.SS "char* log_dir"
The directory for event logs 
.SS "char* profile_dir"
Path for profile directory 
.SS "char* profile_name"
Name the used profile 
.SS "TPML_PCR_SELECTION system_pcrs"
The PCRs used by IMA etc\&. 
.SS "char* tcti"
The used tcti interface 
.SS "char* user_dir"
Directory storing NV objects 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
