.TH "IFAPI_IMA_EVENT" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_IMA_EVENT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_ima_eventlog\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "IFAPI_IMA_EVENT_TYPE \fBtemplate_name\fP"
.br
.ti -1c
.RI "\fBUINT8_ARY\fP \fBtemplate_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
IMA event information 
.SH "Field Documentation"
.PP 
.SS "\fBUINT8_ARY\fP template_value"
The value to be hashed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
