.TH "IFAPI_INFO" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_INFO
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBfapi_version\fP"
.br
.ti -1c
.RI "\fBIFAPI_CONFIG\fP \fBfapi_config\fP"
.br
.ti -1c
.RI "\fBIFAPI_CAP_INFO\fP \fBcap\fP [IFAPI_MAX_CAP_INFO]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBIFAPI_CONFIG\fP fapi_config"
The configuration information 
.SS "char* fapi_version"
The version string of FAPI 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
