.TH "IFAPI_DUPLICATE" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_DUPLICATE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_keystore\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "TPM2B_PRIVATE \fBduplicate\fP"
.br
.ti -1c
.RI "TPM2B_ENCRYPTED_SECRET \fBencrypted_seed\fP"
.br
.ti -1c
.RI "TPM2B_PUBLIC \fBpublic\fP"
.br
.ti -1c
.RI "TPM2B_PUBLIC \fBpublic_parent\fP"
.br
.ti -1c
.RI "char * \fBcertificate\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICY\fP * \fBpolicy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type for representing a FAPI object for key duplication\&. 
.SH "Field Documentation"
.PP 
.SS "char* certificate"
The certificate of the key to be duplicated 
.SS "TPM2B_PRIVATE duplicate"
The duplicate of the key to export 
.SS "TPM2B_ENCRYPTED_SECRET encrypted_seed"
Encrypted seed needed for key import 
.SS "\fBTPMS_POLICY\fP* policy"
The policy of the key to be duplicated 
.SS "TPM2B_PUBLIC public"
The public information of the key to be duplicated 
.SS "TPM2B_PUBLIC public_parent"
The public information of the new parent key 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
