.TH "IFAPI_Entity_ChangeAuth" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_Entity_ChangeAuth
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fapi_int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBentityPath\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBhandle\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP * \fBkey_object\fP"
.br
.ti -1c
.RI "const char * \fBauthValue\fP"
.br
.ti -1c
.RI "TPM2B_AUTH \fBnewAuthValue\fP"
.br
.ti -1c
.RI "TPM2B_PRIVATE * \fBnewPrivate\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP \fBobject\fP"
.br
.ti -1c
.RI "\fBIFAPI_OBJECT\fP \fBhiearchy_object\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBnv_index\fP"
.br
.ti -1c
.RI "\fBESYS_TR\fP \fBhierarchy_handle\fP"
.br
.ti -1c
.RI "char ** \fBpathlist\fP"
.br
.ti -1c
.RI "size_t \fBnumPaths\fP"
.br
.ti -1c
.RI "size_t \fBnumPathsCleanup\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The data structure holding internal state of Fapi_ChangeAuth\&. 
.SH "Field Documentation"
.PP 
.SS "const char* authValue"
The new auth value 
.SS "const char* entityPath"
The implicit key path 
.SS "\fBESYS_TR\fP handle"
The ESYS handle of the key 
.SS "\fBIFAPI_OBJECT\fP hiearchy_object"
Used for copying a hierarchy 
.br
 
.SS "\fBESYS_TR\fP hierarchy_handle"
NV handle of the hierarchy to be changed 
.SS "\fBIFAPI_OBJECT\fP* key_object"
The IPAPI object of the key 
.SS "TPM2B_AUTH newAuthValue"
The new auth value 
.SS "TPM2B_PRIVATE* newPrivate"
New private data created by parend 
.SS "size_t numPaths"
Size of array with all keystore objects 
.SS "size_t numPathsCleanup"
Size of array with all keystore objects 
.SS "\fBESYS_TR\fP nv_index"
NV handle of the object to be changed 
.SS "\fBIFAPI_OBJECT\fP object"
Deserialized NV object or hierarchy 
.SS "char** pathlist"
The array with all keystore objects 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
