.TH "IFAPI_TSS_EVENT" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAPI_TSS_EVENT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_eventlog\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "TPM2B_EVENT \fBdata\fP"
.br
.ti -1c
.RI "char * \fBevent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TSS event information 
.SH "Field Documentation"
.PP 
.SS "TPM2B_EVENT data"
The event data 
.SS "char* event"
TSS event information 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
