.TH "PACKED" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PACKED
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "UINT16 \fBAlgorithmId\fP"
.br
.ti -1c
.RI "UINT8 \fBDigest\fP []"
.br
.ti -1c
.RI "UINT32 \fBEventSize\fP"
.br
.ti -1c
.RI "UINT8 \fBEvent\fP []"
.br
.ti -1c
.RI "UINT32 \fBPCRIndex\fP"
.br
.ti -1c
.RI "UINT32 \fBEventType\fP"
.br
.ti -1c
.RI "UINT32 \fBDigestCount\fP"
.br
.ti -1c
.RI "TCG_DIGEST2 \fBDigests\fP []"
.br
.ti -1c
.RI "char16_t \fBc\fP"
.br
.ti -1c
.RI "uuid_t \fBVariableName\fP"
.br
.ti -1c
.RI "UINT64 \fBUnicodeNameLength\fP"
.br
.ti -1c
.RI "UINT64 \fBVariableDataLength\fP"
.br
.ti -1c
.RI "char16_t \fBUnicodeName\fP []"
.br
.ti -1c
.RI "UEFI_PHYSICAL_ADDRESS \fBBlobBase\fP"
.br
.ti -1c
.RI "UINT64 \fBBlobLength\fP"
.br
.ti -1c
.RI "UINT32 \fBpcrIndex\fP"
.br
.ti -1c
.RI "UINT32 \fBeventType\fP"
.br
.ti -1c
.RI "BYTE \fBdigest\fP [20]"
.br
.ti -1c
.RI "UINT32 \fBeventDataSize\fP"
.br
.ti -1c
.RI "BYTE \fBevent\fP []"
.br
.ti -1c
.RI "UINT16 \fBalgorithmId\fP"
.br
.ti -1c
.RI "UINT16 \fBdigestSize\fP"
.br
.ti -1c
.RI "UINT8 \fBvendorInfoSize\fP"
.br
.ti -1c
.RI "BYTE \fBvendorInfo\fP []"
.br
.ti -1c
.RI "BYTE \fBSignature\fP [16]"
.br
.ti -1c
.RI "UINT32 \fBplatformClass\fP"
.br
.ti -1c
.RI "UINT8 \fBspecVersionMinor\fP"
.br
.ti -1c
.RI "UINT8 \fBspecVersionMajor\fP"
.br
.ti -1c
.RI "UINT8 \fBspecErrata\fP"
.br
.ti -1c
.RI "UINT8 \fBuintnSize\fP"
.br
.ti -1c
.RI "UINT32 \fBnumberOfAlgorithms\fP"
.br
.ti -1c
.RI "TCG_SPECID_ALG \fBdigestSizes\fP []"
.br
.ti -1c
.RI "UEFI_PHYSICAL_ADDRESS \fBImageLocationInMemory\fP"
.br
.ti -1c
.RI "UINT64 \fBImageLengthInMemory\fP"
.br
.ti -1c
.RI "UINT64 \fBImageLinkTimeAddress\fP"
.br
.ti -1c
.RI "UINT64 \fBLengthOfDevicePath\fP"
.br
.ti -1c
.RI "BYTE \fBDevicePath\fP []"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
