.TH "policy_object_node" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
policy_object_node
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_policy_execute\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBpath\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICY\fP \fBpolicy\fP"
.br
.ti -1c
.RI "struct \fBpolicy_object_node\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
List of policies which fulfill a certain predicate\&.
.PP
The elements are stored in a linked list\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBpolicy_object_node\fP* next"
Pointer to next element 
.SS "const char* path"
The path of the policy object 
.SS "\fBTPMS_POLICY\fP policy"
The policy object 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
