.TH "template_field" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
template_field
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBfield_id\fP"
.br
.ti -1c
.RI "TSS2_RC(* \fBfield_cb\fP )(UINT8 *digest, UINT8 *buffer, size_t *offset, json_object *jso, \fBIFAPI_IMA_TEMPLATE\fP *template)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
