.TH "tpm_getekcertificate_ctx" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tpm_getekcertificate_ctx
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBec_cert_path\fP"
.br
.ti -1c
.RI "FILE * \fBec_cert_file_handle\fP"
.br
.ti -1c
.RI "char * \fBek_server_addr\fP"
.br
.ti -1c
.RI "unsigned int \fBSSL_NO_VERIFY\fP"
.br
.ti -1c
.RI "char * \fBek_path\fP"
.br
.ti -1c
.RI "bool \fBverbose\fP"
.br
.ti -1c
.RI "bool \fBis_tpm2_device_active\fP"
.br
.ti -1c
.RI "TPM2B_PUBLIC * \fBout_public\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
