.TH "TPML_POLICYBRANCHES" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPML_POLICYBRANCHES
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_policy_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "UINT32 \fBcount\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYBRANCH\fP \fBauthorizations\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Policy type \fBTPML_POLICYBRANCHES\fP 
.SH "Field Documentation"
.PP 
.SS "\fBTPMS_POLICYBRANCH\fP authorizations[]"
Array of policy elements 
.SS "UINT32 count"
None 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
