.TH "TPMS_POLICYSECRET" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPMS_POLICYSECRET
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_policy_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "TPM2B_NONCE \fBnonceTPM\fP"
.br
.ti -1c
.RI "TPM2B_DIGEST \fBcpHashA\fP"
.br
.ti -1c
.RI "TPM2B_NONCE \fBpolicyRef\fP"
.br
.ti -1c
.RI "INT32 \fBexpiration\fP"
.br
.ti -1c
.RI "char * \fBobjectPath\fP"
.br
.ti -1c
.RI "TPM2B_NAME \fBobjectName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Policy type \fBTPMS_POLICYSECRET\fP 
.SH "Field Documentation"
.PP 
.SS "TPM2B_DIGEST cpHashA"
None 
.SS "INT32 expiration"
None 
.SS "TPM2B_NONCE nonceTPM"
None 
.SS "TPM2B_NAME objectName"
Public name of the object 
.SS "char* objectPath"
Path of the object 
.SS "TPM2B_NONCE policyRef"
Default is zero length 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
