.TH "TPMS_POLICYAUTHORIZENV" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPMS_POLICYAUTHORIZENV
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_policy_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBnvPath\fP"
.br
.ti -1c
.RI "TPMS_NV_PUBLIC \fBnvPublic\fP"
.br
.ti -1c
.RI "TPM2B_DIGEST \fBpolicy\fP"
.br
.ti -1c
.RI "TPMT_HA \fBnv_policy\fP"
.br
.ti -1c
.RI "uint8_t * \fBpolicy_buffer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Policy type \fBTPMS_POLICYAUTHORIZENV\fP 
.SH "Field Documentation"
.PP 
.SS "TPMT_HA nv_policy"
Policy stored in NV ram 
.SS "char* nvPath"
None 
.SS "TPMS_NV_PUBLIC nvPublic"
None 
.SS "TPM2B_DIGEST policy"
Policy Digest 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
