.TH "TPMS_POLICY" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPMS_POLICY
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_policy_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBdescription\fP"
.br
.ti -1c
.RI "TPML_DIGEST_VALUES \fBpolicyDigests\fP"
.br
.ti -1c
.RI "struct \fBTPML_POLICYAUTHORIZATIONS\fP * \fBpolicyAuthorizations\fP"
.br
.ti -1c
.RI "struct \fBTPML_POLICYELEMENTS\fP * \fBpolicy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Policy type \fBTPMS_POLICY\fP 
.SH "Field Documentation"
.PP 
.SS "char* description"
O 
.SS "struct \fBTPML_POLICYELEMENTS\fP* policy"
X 
.SS "struct \fBTPML_POLICYAUTHORIZATIONS\fP* policyAuthorizations"
O 
.SS "TPML_DIGEST_VALUES policyDigests"
O 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
