.TH "TPMS_POLICYTEMPLATE" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPMS_POLICYTEMPLATE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_policy_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "TPM2B_DIGEST \fBtemplateHash\fP"
.br
.ti -1c
.RI "TPM2B_PUBLIC \fBtemplatePublic\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Policy type \fBTPMS_POLICYTEMPLATE\fP 
.SH "Field Documentation"
.PP 
.SS "TPM2B_DIGEST templateHash"
None 
.SS "TPM2B_PUBLIC templatePublic"
None 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
