.TH "TPMS_POLICYCOUNTERTIMER" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPMS_POLICYCOUNTERTIMER
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_policy_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "TPM2B_OPERAND \fBoperandB\fP"
.br
.ti -1c
.RI "UINT16 \fBoffset\fP"
.br
.ti -1c
.RI "TPM2_EO \fBoperation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Policy type \fBTPMS_POLICYCOUNTERTIMER\fP 
.SH "Field Documentation"
.PP 
.SS "UINT16 offset"
Default is 0 
.SS "TPM2B_OPERAND operandB"
None 
.SS "TPM2_EO operation"
None 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
