.TH "TPMS_POLICYCOMMANDCODE" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPMS_POLICYCOMMANDCODE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_policy_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "TPM2_CC \fBcode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Policy type \fBTPMS_POLICYCOMMANDCODE\fP 
.SH "Field Documentation"
.PP 
.SS "TPM2_CC code"
None 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
