.TH "TPMU_POLICYELEMENT" 3 "Mon May 15 2023" "Version 4.0.1-44-g8699ab39" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPMU_POLICYELEMENT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifapi_policy_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTPMS_POLICYOR\fP \fBPolicyOr\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYSIGNED\fP \fBPolicySigned\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYSECRET\fP \fBPolicySecret\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYPCR\fP \fBPolicyPCR\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYLOCALITY\fP \fBPolicyLocality\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYNV\fP \fBPolicyNV\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYCOUNTERTIMER\fP \fBPolicyCounterTimer\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYCOMMANDCODE\fP \fBPolicyCommandCode\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYPHYSICALPRESENCE\fP \fBPolicyPhysicalPresence\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYCPHASH\fP \fBPolicyCpHash\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYNAMEHASH\fP \fBPolicyNameHash\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYDUPLICATIONSELECT\fP \fBPolicyDuplicationSelect\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYAUTHORIZE\fP \fBPolicyAuthorize\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYAUTHVALUE\fP \fBPolicyAuthValue\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYPASSWORD\fP \fBPolicyPassword\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYNVWRITTEN\fP \fBPolicyNvWritten\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYTEMPLATE\fP \fBPolicyTemplate\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYAUTHORIZENV\fP \fBPolicyAuthorizeNv\fP"
.br
.ti -1c
.RI "\fBTPMS_POLICYACTION\fP \fBPolicyAction\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
[u''] 
.SH "Field Documentation"
.PP 
.SS "\fBTPMS_POLICYACTION\fP PolicyAction"
None 
.SS "\fBTPMS_POLICYAUTHORIZE\fP PolicyAuthorize"
None 
.SS "\fBTPMS_POLICYAUTHORIZENV\fP PolicyAuthorizeNv"
None 
.SS "\fBTPMS_POLICYAUTHVALUE\fP PolicyAuthValue"
None 
.SS "\fBTPMS_POLICYCOMMANDCODE\fP PolicyCommandCode"
None 
.SS "\fBTPMS_POLICYCOUNTERTIMER\fP PolicyCounterTimer"
None 
.SS "\fBTPMS_POLICYCPHASH\fP PolicyCpHash"
None 
.SS "\fBTPMS_POLICYDUPLICATIONSELECT\fP PolicyDuplicationSelect"
None 
.SS "\fBTPMS_POLICYLOCALITY\fP PolicyLocality"
None 
.SS "\fBTPMS_POLICYNAMEHASH\fP PolicyNameHash"
None 
.SS "\fBTPMS_POLICYNV\fP PolicyNV"
None 
.SS "\fBTPMS_POLICYNVWRITTEN\fP PolicyNvWritten"
None 
.SS "\fBTPMS_POLICYOR\fP PolicyOr"
None 
.SS "\fBTPMS_POLICYPASSWORD\fP PolicyPassword"
None 
.SS "\fBTPMS_POLICYPCR\fP PolicyPCR"
None 
.SS "\fBTPMS_POLICYPHYSICALPRESENCE\fP PolicyPhysicalPresence"
None 
.SS "\fBTPMS_POLICYSECRET\fP PolicySecret"
None 
.SS "\fBTPMS_POLICYSIGNED\fP PolicySigned"
None 
.SS "\fBTPMS_POLICYTEMPLATE\fP PolicyTemplate"
None 

.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
